package EncherAnglaise;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import jade.core.ProfileImpl;
import jade.util.ExtendedProperties;
import jade.util.leap.Properties;
import jade.wrapper.AgentController;
import jade.wrapper.ContainerController;
import jade.wrapper.StaleProxyException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ABEDSSAMED
 */
public class EncherForme extends javax.swing.JFrame {

    /**
     * Creates new form EncherForme
     */
    jade.wrapper.AgentContainer container = null;
    AgentController agentController1 = null;
    public static String Text = "";

    String Newligne = System.getProperty("line.separator");

    public static int prixinit = 0;

    public EncherForme() {
        initComponents();
        nombre_iteration.setVisible(false);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NomVendeur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NomProduit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Vend_Prix_Reserve = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Nbr_Acheteur = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Prix_Max_Max = new javax.swing.JTextField();
        Min_Mise = new javax.swing.JTextField();
        Max_Mise = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        nombre_iteration = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ExecutionVend = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sytème d'echère");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 0, 204));

        jPanel3.setBackground(new java.awt.Color(102, 0, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Nom de produit :");

        NomVendeur.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        NomVendeur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NomVendeur.setText("ABDESSAMED");
        NomVendeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomVendeurActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Vendeur :");

        NomProduit.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        NomProduit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NomProduit.setText("MS E250");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Prix de reserve  :");

        Vend_Prix_Reserve.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Vend_Prix_Reserve.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Vend_Prix_Reserve.setText("5000");
        Vend_Prix_Reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Vend_Prix_ReserveActionPerformed(evt);
            }
        });
        Vend_Prix_Reserve.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Vend_Prix_ReserveKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomProduit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Vend_Prix_Reserve, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NomVendeur, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(312, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(NomVendeur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vend_Prix_Reserve, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(102, 0, 204));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("Min mise :");

        Nbr_Acheteur.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Nbr_Acheteur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nbr_Acheteur.setText("4");
        Nbr_Acheteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nbr_AcheteurActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Nombre d'achteur :");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setText("Max mise:");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setText("Prix Max  :");

        Prix_Max_Max.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Prix_Max_Max.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Prix_Max_Max.setText("7500");
        Prix_Max_Max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prix_Max_MaxActionPerformed(evt);
            }
        });

        Min_Mise.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Min_Mise.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Min_Mise.setText("500");
        Min_Mise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Min_MiseActionPerformed(evt);
            }
        });

        Max_Mise.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Max_Mise.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Max_Mise.setText("1000");
        Max_Mise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Max_MiseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Prix_Max_Max, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Min_Mise, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nbr_Acheteur, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Max_Mise, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nbr_Acheteur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Min_Mise, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Max_Mise, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prix_Max_Max, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(102, 0, 204));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Start ");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nombre_iteration.setText("2");
        nombre_iteration.setEnabled(false);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("|Enchère anglaise");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(nombre_iteration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_iteration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        ExecutionVend.setColumns(20);
        ExecutionVend.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        ExecutionVend.setRows(5);
        jScrollPane1.setViewportView(ExecutionVend);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Enchère :");

        jButton2.setBackground(new java.awt.Color(102, 0, 204));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setText("Afficher gagnat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EncherAnglaise/Windows_Close_Program_22531 (1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void APP() {
        jade.core.Runtime runtime = jade.core.Runtime.instance();
        ProfileImpl profile = new ProfileImpl();
        ContainerController CC = runtime.createMainContainer(profile);
        ArrayList<AgentController> acheteurs = new ArrayList<AgentController>();
        ArrayList<String> ListeNomAcheteurs = new ArrayList<String>();

        String Nom_Vend = NomVendeur.getText();

        String Nom_Prod = NomProduit.getText();
        // float VendPrixInit = Float.valueOf(Vend_Prix_Init.getText()).floatValue();
        float VendPrixRes = Float.valueOf(Vend_Prix_Reserve.getText()).floatValue();

        Integer NbrItr = Integer.valueOf(nombre_iteration.getText()).intValue();;

        int NbrAch = Integer.valueOf(Nbr_Acheteur.getText()).intValue();
        float MinMise = Float.valueOf(Min_Mise.getText()).floatValue();
        float MaxMise = Integer.valueOf(Max_Mise.getText()).floatValue();
        float Mise;

        float MaxPrixMin = VendPrixRes;
        float MaxPrixMax = Float.valueOf(Prix_Max_Max.getText()).floatValue();
        float MaxPrix;

        for (int i = 0; i < NbrAch; i++) {
            // ajouter la mise et le max PRIX pour chaque acheteurs 
            Mise = (float) Math.floor(Math.random() * (MaxMise - MinMise) + MinMise);
            MaxPrix = (float) Math.floor(Math.random() * (MaxPrixMax - MaxPrixMin) + MaxPrixMin);

            Object[] Argument_Ach = new Object[6];
            Argument_Ach[0] = Nom_Vend;
            Argument_Ach[1] = VendPrixRes;
            Argument_Ach[2] = Mise;
            Argument_Ach[3] = MaxPrix;
            Argument_Ach[4] = this;
            Argument_Ach[5] = NbrAch;
            Argument_Ach[5] = MaxMise;

            if (VendPrixRes < MaxPrix) {
                ListeNomAcheteurs.add("Ach" + i);
                try {
                    acheteurs.add(CC.createNewAgent("Ach" + i, "Acheteur", Argument_Ach));
                } catch (StaleProxyException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            } else {
                Text = Text + Newligne + "je suis l'acheteur Ach" + i + Newligne + " mon prix max :" + MaxPrix + " est inferieur au prix initial" + VendPrixRes + Newligne + "je ne rentre pas dans l'enchere";
                System.out.println(Text);
            }
        }

        for (int i = 0; i < acheteurs.size(); i++) {
            try {
                acheteurs.get(i).start();
            } catch (StaleProxyException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }

        Object[] Argument_Vend = new Object[6];
        Argument_Vend[0] = VendPrixRes;
        Argument_Vend[1] = VendPrixRes;
        Argument_Vend[2] = Nom_Prod;
        Argument_Vend[3] = NbrItr;
        Argument_Vend[4] = ListeNomAcheteurs;
        Argument_Vend[5] = this;

        AgentController Vendeur;
        try {
            Vendeur = CC.createNewAgent(Nom_Vend, "Vendeur", Argument_Vend);
            Vendeur.start();
        } catch (StaleProxyException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }


    private void NomVendeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomVendeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomVendeurActionPerformed

    private void Prix_Max_MaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prix_Max_MaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Prix_Max_MaxActionPerformed

    private void Nbr_AcheteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nbr_AcheteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nbr_AcheteurActionPerformed

    private void Min_MiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Min_MiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Min_MiseActionPerformed

    private void Max_MiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Max_MiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Max_MiseActionPerformed

    private void Vend_Prix_ReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Vend_Prix_ReserveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Vend_Prix_ReserveActionPerformed
    public static String nomeavend;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String names[];
        names = new String[]{"Aymen", "Mohamed", "Meroua", "Reda", "Yasmine", "Ghiles", "Sonia", "Abdelhakim", "Abderraouf", "Stiven"};
        ExecutionVend.setText("");
        Text = "";
        jade.core.Runtime runtime = jade.core.Runtime.instance();
       // Properties p = new ExtendedProperties();
        //p.setProperty("gui", "true");
        ProfileImpl profile = new ProfileImpl();
        ContainerController CC = runtime.createMainContainer(profile);
        ArrayList<AgentController> acheteurs = new ArrayList<AgentController>();

        ArrayList<String> ListeNomAcheteurs = new ArrayList<String>();

        String Nom_Vend = NomVendeur.getText();
        nomeavend = NomVendeur.getText();
        String Nom_Prod = NomProduit.getText();
        //   float VendPrixInit = Float.valueOf(Vend_Prix_Init.getText()).floatValue();
        float VendPrixRes = Float.valueOf(Vend_Prix_Reserve.getText()).floatValue();

        Integer NbrItr = Integer.valueOf(nombre_iteration.getText()).intValue();

        int NbrAch = Integer.valueOf(Nbr_Acheteur.getText()).intValue();
        float MinMise = Float.valueOf(Min_Mise.getText()).floatValue();
        float MaxMise = Integer.valueOf(Max_Mise.getText()).floatValue();
        float Mise;

        float MaxPrixMin = VendPrixRes;
        float MaxPrixMax = Float.valueOf(Prix_Max_Max.getText()).floatValue();
        float MaxPrix;

        for (int i = 0; i < NbrAch; i++) {
            Mise = (float) Math.floor(Math.random() * (MaxMise - MinMise) + MinMise);
            MaxPrix = (float) Math.floor(Math.random() * (MaxPrixMax - MaxPrixMin) + MaxPrixMin);
            // EncherForme.ExecutionVend.append("\n" + "Je suis l'achrteur :" + i + "\n Mon mise est :" + Mise + "Mon Prix Max est : " + MaxPrix);
            Object[] Argument_Ach = new Object[6];
            Argument_Ach[0] = Nom_Vend;
            Argument_Ach[1] = VendPrixRes;
            Argument_Ach[2] = Mise;
            Argument_Ach[3] = MaxPrix;
            Argument_Ach[4] = this;
            Argument_Ach[5] = NbrAch;

            if (VendPrixRes < MaxPrix) {
                ListeNomAcheteurs.add(names[i]);
                try {
                    acheteurs.add(CC.createNewAgent(names[i], "EncherAnglaise.Acheteur", Argument_Ach));

                } catch (StaleProxyException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                }
            } else {
                Text = Text + Newligne + "je suis l'Acheteur" + i + Newligne + " mon prix max :" + MaxPrix + " est inferieur au prix initial" + VendPrixRes + Newligne + "je ne rentre pas dans l'enchere";
                System.out.println(Text);
            }
        }

        for (int i = 0; i < acheteurs.size(); i++) {
            try {
                acheteurs.get(i).start();
            } catch (StaleProxyException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            }
        }

        Object[] Argument_Vend = new Object[6];
        Argument_Vend[0] = VendPrixRes;
        Argument_Vend[1] = VendPrixRes;
        Argument_Vend[2] = Nom_Prod;
        Argument_Vend[3] = NbrItr;
        Argument_Vend[4] = ListeNomAcheteurs;
        Argument_Vend[5] = this;

        AgentController Vendeur;
        try {
            System.out.println("Nom_Vend" + Nom_Vend);
            Vendeur = CC.createNewAgent(Nom_Vend, "EncherAnglaise.Vendeur", Argument_Vend);
            Vendeur.start();
        } catch (StaleProxyException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(EncherForme.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(EncherAnglaise.Vendeur.bidedAgent);
        Gagnant gg = new Gagnant(NomProduit.getText(), EncherAnglaise.Vendeur.bidedAgent + "", EncherAnglaise.Vendeur.lastPrix);
        gg.show();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println(EncherAnglaise.Vendeur.bidedAgent);
        Gagnant gg = new Gagnant(NomProduit.getText(), Vendeur.bidedAgent + "", Vendeur.lastPrix);
        gg.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Vend_Prix_ReserveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Vend_Prix_ReserveKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Vend_Prix_ReserveKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.hide();
        MainApp mp=new MainApp();
        mp.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EncherForme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EncherForme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EncherForme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EncherForme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EncherForme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea ExecutionVend;
    private javax.swing.JTextField Max_Mise;
    private javax.swing.JTextField Min_Mise;
    private javax.swing.JTextField Nbr_Acheteur;
    private javax.swing.JTextField NomProduit;
    private javax.swing.JTextField NomVendeur;
    private javax.swing.JTextField Prix_Max_Max;
    private javax.swing.JTextField Vend_Prix_Reserve;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre_iteration;
    // End of variables declaration//GEN-END:variables
}
